kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16265402345689761
    roll: -0
    pitch: 0
    yaw: -5.0723914245959241e-08
  upper_arm:
    x: 0.00014080666764870406
    y: 0
    z: 0
    roll: 1.5704537403998009
    pitch: 0
    yaw: 5.1627976847219563e-06
  forearm:
    x: -0.42536146720208223
    y: 0
    z: 0
    roll: 3.1408759506500368
    pitch: 3.1410599072783811
    yaw: 3.1415913438172729
  wrist_1:
    x: -0.39230678266726493
    y: -0.00021885016220067415
    z: 0.13385894093442383
    roll: 0.0016349297676925209
    pitch: 0.0003736320900270765
    yaw: 1.6403462693999222e-06
  wrist_2:
    x: 0.00018681521260161351
    y: -0.099631118327767706
    z: 8.8097875261335448e-05
    roll: 1.5699120864713982
    pitch: 0
    yaw: 6.0079895574174924e-07
  wrist_3:
    x: 0.00010142093628044386
    y: 0.099445823148790621
    z: 3.4258744487455513e-05
    roll: 1.57114082334636
    pitch: 3.1415926535897931
    yaw: 3.1415925148062795
  hash: calib_10589897412296645486