# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robotiq_gripper_controller
    - scaled_joint_trajectory_controller

  robotiq_gripper_controller:
    type: GripperCommand
    joints:
      - robotiq_85_left_knuckle_joint
    action_ns: gripper_cmd
    default: true

  scaled_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true